### ISSUE TITLE
Add support for multiple camera feeds

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/qgroundcontrol#6] opened 2017-06-01 02:07 UTC
Perhaps using multiple picture-in-picture windows across the bottom.

**Comment by jaxxzer** [comment] 2018-04-10 02:53
Of interest: https://github.com/Dronecode/camera-streaming-daemon

**Comment by patrickelectric** [comment] 2019-03-25 11:21
Duplicate of: https://github.com/mavlink/qgroundcontrol/issues/5260

**Closed by patrickelectric** 2019-03-25 11:21 UTC
Labels: feature
