### ISSUE TITLE
Add support for multicast streams

### ISSUE THREAD

**Issue by jaxxzer** [bluerobotics/qgroundcontrol#215] opened 2018-10-17 14:45 UTC

**Comment by jaxxzer** [comment] 2019-03-19 15:05
The idea here is to allow more than one application to access the video stream on a single udp port.

**Comment by zt-luo** [comment] 2019-03-20 11:00
> The idea here is to allow more than one application to access the video stream on a single udp port.

why not add more UDP port on companion computer.

**Comment by patrickelectric** [comment] 2019-03-20 14:16
Duplicate of https://github.com/mavlink/qgroundcontrol/issues/5260.
@zt-luo the problem is in QGC side not companion.

**Closed as completed by patrickelectric** 2019-03-20 14:16 UTC
Labels: upstream, confirm
